name: Transform GeoNames data to RDF

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./download.sh
      - run: ./map.sh
      - uses: actions/upload-artifact@v4
        with:
          name: geonames-ttl
          path: output/geonames.ttl
      - run: zip -r output/geonames.zip output/geonames.ttl
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.S3_ACCESS_KEY}}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
          space_name: geonames
          space_region: ams3
          source: output/geonames.zip

