name: Transform GeoNames data to RDF

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./download.sh
      - run: ./map.sh
      - uses: actions/upload-artifact@v4
        with:
          name: geonames-ttl
          path: data/geonames.ttl

